# Multivariada

Entrada dos dados

Dados entre parênteses são os valores observados das respectivas variáveis, X1, X2, X3, X4 e X5.

```{r}
X1<-c(0.0475,0.04715,0.0471,0.0469,0.0469,0.04635)
X2<-c(0.366,0.359,0.341,0.348,0.351,0.350)
X3<-c(0.388,0.345,0.367,0.353,0.355,0.426)
X4<-c(0.302,0.296,0.279,0.286,0.285,0.279)
X5<-c(1.29,1.16,1.31,1.23,1.24,1.52)
```

```{r}
Y<-cbind(X1,X2,X3,X4,X5)

```

```{r}
S<-cov(cbind(X1,X2,X3,X4,X5)); 
S

```


```{r}
autoS<-eigen(S); 
autoS

```

```{r}
S<-cov(cbind(X1,X2,X3,X4,X5))

```

```{r}
S<-cov(cbind(X1,X2,X3,X4,X5)); 
S

```


```{r}
autoS<-eigen(S); 
autoS

```

```{r}
S.cov<-prcomp(cbind(X1,X2,X3,X4,X5))

```

```{r}
summary(S.cov)

```


```{r}
screeplot(S.cov,type="lines")

```

Resultados a partir da matriz de covariância

```{r}
R<-cor(cbind(X1,X2,X3,X4,X5)); 
R

```

```{r}
autoR<-eigen(R);
autoR
```

```{r}
SR<-prcomp(cbind(X1,X2,X3,X4,X5), cor=TRUE, scale=TRUE)
SR
```

```{r}
summary(SR)

```

```{r}
scores<-SR$x;
scores
```

Resultados a partir da matriz de correlação R
```{r}
screeplot(SR,type="lines")
```

Dispersão gráfica
```{r}
biplot(SR)
```


